date_columns:
  - DOB
  - HivTestDate
  - ARTStartDate
  - CurrentARTRegimenDispensationDate
  - Current_CD4_countdate
  - Current_VL_date
  - Patient_status_date
  - ANCVisitDate
  - FirstInteraction_date
  - LastInteraction_date
  - NextAppointmentDate
  - Prescriptiondate
  - estimateddateofdelivery
  - report_period

input_path_plus:
  - /Users/johnnjenga/Downloads/Zambia_ETL/data/scplus_art_cohort_5_5_v2.csv

input_path_legacy:
  /Users/johnnjenga/Downloads/Zambia_ETL/data/SCL_ART_Cohort_30052024.csv

report_period:
  - 2024-03-13
  
